# Generated by Django 4.2.5 on 2023-09-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, verbose_name='Nome Cargo')),
                ('salario', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Salario')),
                ('comissao', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Comissão')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('telefone', models.IntegerField(blank=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('cartao', models.CharField(max_length=20, verbose_name='Cartão')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('telefone', models.IntegerField(blank=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
