# Generated by Django 4.2.5 on 2023-10-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, verbose_name='Nome Cargo')),
                ('carga_horaria', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Carga horária')),
                ('comissao', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Comissão')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('telefone', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('telefone', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Salario')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, unique=True, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Peso')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Marca')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('Feito', 'Feito'), ('Finalizado', 'Finalizado'), ('Andamento', 'Andamento')])),
                ('cliente_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cliente')),
                ('funcionario_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.funcionario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Pedida')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.produto')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.pedido')),
            ],
            options={
                'verbose_name': 'Item Pedido',
                'verbose_name_plural': 'Items Pedido',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('numero', models.IntegerField(verbose_name='Número ')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('pais', models.CharField(max_length=200, verbose_name='País')),
                ('uf', models.CharField(default=None, max_length=200, verbose_name='UF')),
                ('endereco_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, unique=True, verbose_name='Número Cartão')),
                ('senha', models.CharField(max_length=200, verbose_name='Senha Cartão')),
                ('pessoa_Dona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cliente')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
