# Generated by Django 4.2.5 on 2023-09-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='salario',
        ),
        migrations.AddField(
            model_name='cargo',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Carga horária'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cartao'),
        ),
    ]
