# Generated by Django 4.2.5 on 2023-10-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_remove_cliente_telefone_remove_funcionario_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='telefone_cliente',
        ),
    ]
