# Generated by Django 4.2.5 on 2023-09-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_remove_cargo_salario_cargo_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Salario'),
        ),
    ]
