# Generated by Django 4.2.5 on 2023-10-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_remove_cliente_login_remove_cliente_senha_and_more'),
        ('aplic', '0004_remove_telefone_telefone_cliente'),
    ]

    operations = [
    ]
