# Generated by Django 4.2.5 on 2023-09-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='_estoque',
            new_name='estoque',
        ),
    ]
