# Generated by Django 4.2.5 on 2023-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_merge_20231005_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='pessoa_Dona',
            new_name='pessoa_dona',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='senha',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(verbose_name='Número '),
        ),
    ]
