# Generated by Django 4.2.5 on 2023-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_rename__estoque_produto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=4, verbose_name='Número ')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('pais', models.CharField(max_length=200, verbose_name='País')),
                ('utc', models.CharField(max_length=200, verbose_name='UTC')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
