# Generated by Django 4.2.5 on 2023-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_rename_pessoa_dona_cartao_pessoa_dona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='endereco_fornecedor',
        ),
        migrations.AddField(
            model_name='endereco',
            name='status',
            field=models.CharField(choices=[('Funcionario', 'Funcionario'), ('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor')], default=2),
            preserve_default=False,
        ),
    ]
