# Generated by Django 4.2.5 on 2023-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_endereco_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='numero',
            field=models.CharField(max_length=12, unique=True, verbose_name='Número Cartão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome da Marca'),
        ),
    ]
