# Generated by Django 4.2.5 on 2023-10-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_remove_endereco_endereco_fornecedor_endereco_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='status',
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor'),
        ),
    ]
