# Generated by Django 4.2.5 on 2023-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_alter_cartao_numero_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
