# Generated by Django 4.2.5 on 2023-10-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_remove_endereco_status_endereco_endereco_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cliente'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.funcionario'),
        ),
    ]
