# Generated by Django 4.2.5 on 2023-09-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cartao'),
        ),
    ]
