# Generated by Django 4.2.5 on 2023-10-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_alter_endereco_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='endereco_cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.cliente'),
        ),
    ]
