# Generated by Django 4.2.5 on 2023-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_alter_fornecedor_cnpj_alter_produto_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do Produto'),
        ),
    ]
