# Generated by Django 4.2.5 on 2023-10-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_alter_endereco_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='telefone_cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.cliente'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='telefone_funcionario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.funcionario'),
        ),
    ]
