# Generated by Django 4.2.5 on 2023-10-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_produto_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item Pedido')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('status', models.BooleanField(verbose_name='Status do pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
