# Generated by Django 4.2.5 on 2023-10-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_telefone_telefone_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='telefone_fornecedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor'),
        ),
    ]
