# Generated by Django 4.2.6 on 2023-10-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_alter_telefone_telefone_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mercado', models.CharField(max_length=50, unique=True, verbose_name='Nome do Mercado')),
                ('cnpj_mercado', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('numero_telefone_mercado', models.CharField(max_length=11, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
            },
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='numero',
            new_name='numero_cartao',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='numero',
            new_name='numero_casa',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='nome_fornecedor',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='item',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='numero_telefone',
        ),
    ]
