# Generated by Django 4.2.5 on 2023-11-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0017_alter_cliente_options_cliente_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default=1, max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
