# Generated by Django 4.2.5 on 2023-10-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0018_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Feito', 'Feito'), ('Finalizado', 'Finalizado')]),
        ),
    ]
