# Generated by Django 4.2.5 on 2023-10-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0020_remove_pedido_item_alter_endereco_cep_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPdeido',
            new_name='ItemPedido',
        ),
    ]
