# Generated by Django 4.2.5 on 2023-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0022_alter_itempedido_options_alter_itempedido_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cartao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=100, unique=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(max_length=100, unique=True, verbose_name='Senha'),
        ),
    ]
