# Generated by Django 4.2.5 on 2023-10-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0024_alter_cliente_senha_alter_funcionario_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
    ]
