# Generated by Django 4.2.5 on 2023-10-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0026_alter_endereco_options_cliente_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.pedido'),
        ),
    ]
