# Generated by Django 4.2.5 on 2023-10-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0028_remove_cliente_cartao_cartao_pessoa_dona'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor'),
        ),
    ]
